FROM node

WORKDIR /usr/src/app

# Update Packages and install common deps
RUN apt-get update
RUN apt-get upgrade -y

# Install node, NPM and GIT
RUN apt-get install curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
RUN apt-get install -y git

# Copy all files to the image
COPY . .

# Get project from bitbucket
RUN git clone https://MateusVMachado:3yfpmswwqb2BPn8EMAdc@bitbucket.org/viasoftkorp/etm-backend.git

# Copy all files and directories from etm-backend to the root directory
RUN cp -r ./etm-backend/. ./
RUN rm -r ./etm-backend/

RUN cp -rf mongoAccess.model.ts ./src/models/
RUN cp -rf server.ts ./src/

# Install packages
RUN npm i

# Compile and execute
RUN npm run grunt
CMD ["npm", "start"]
